version: '3.5'
services:
  web:
    image: ${IMG_NAME}
    container_name: web_server
    restart: always
    ports:
      - "1423:1423"
    environment:
      SERVER_PORT: 1423
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASSWD: 123456
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWD: 123456
      MYSQL_DB: ${DB_NAME}
  mysql:
    image: mysql:8.0.27
    container_name: mysql
    restart: always
    ports:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Shanghai
      MYSQL_ROOT_HOST: '%'
  redis:
    image: redis:7.0.0
    container_name: redis
    restart: always
    ports:
      - "6379"
    command: redis-server --requirepass 123456
    volumes:
      - redis-data:/data


volumes:
  mysql-data:
  redis-data: